export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_FAILED = 'FETCH_BANNER_FAILED';
export const START_LOADING_BANNER = 'START_LOADING_BANNER';
export const STOP_LOADING_BANNER = 'STOP_LOADING_BANNER';