//Banner type
export const FETCH_BANNER_REQUEST = 'FETCH_BANNER_REQUEST'
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS'
export const FETCH_BANNER_FAILED = 'FETCH_BANNER_FAILED'
//Movie Page
export const FETCH_MOVIEPAGE_REQUEST = 'FETCH_MOVIEPAGE_REQUEST'
export const FETCH_MOVIEPAGE_SUCCESS = 'FETCH_MOVIEPAGE_SUCCESS'
export const FETCH_MOVIEPAGE_FAILED = 'FETCH_MOVIEPAGE_FAILED'
//Change Page
export const CHANGE_PAGE_PREV = 'CHANGE_PAGE_PREV'
export const CHANGE_PAGE_NEXT = 'CHANGE_PAGE_NEXT'
//
