export const FETCH_INFO_SHOWTIMES_REQUEST = 'FETCH_INFO_SHOWTIMES_REQUEST'
export const FETCH_INFO_SHOWTIMES_SUCCESS = 'FETCH_INFO_SHOWTIMES_SUCCESS'
export const FETCH_INFO_SHOWTIMES_FAILED = 'FETCH_INFO_SHOWTIMES_FAILED'
